name=LEGOPowerFunctions
version=1.0.0
author=schultzy51
maintainer=unknown
sentence=Control LEGO Power Functions motors with Arduino
paragraph=Send IR signals to LEGO PF receivers.
category=Device Control
url=https://github.com/schultzy51/LEGOPowerFunctions
architectures=*